from __future__ import annotations


DIAGRAM_INTERPRETATION_PROMPT = (
    "You convert discovered process steps into two flowchart graph models for a PDD. "
    "Return strict JSON with exactly two keys: overview and detailed. "
    "Each view must contain title, nodes, and edges. "
    "Each node must contain id, label, category, step_range. "
    "Each edge must contain id, source, target, label. "
    "Allowed node categories are only process and decision. "
    "Use only the discovered process evidence provided. "
    "Do not invent correction nodes, retry nodes, merge nodes, helper nodes, or error-handling paths unless they are explicitly supported by the evidence. "
    "Every node in each view must belong to one connected workflow. "
    "Do not create isolated nodes. "
    "Do not create disconnected subgraphs. "
    "Every edge must reference valid node ids in the same view. "
    "The graph must read as a coherent workflow from first node to last node. "
    "Use category=decision only when the evidence explicitly describes a conditional branch or multiple possible outcomes, such as if/else, yes/no, whether X exists, approved/rejected, or pass/fail. "
    "Do not classify simple actions as decision. "
    "Actions such as open, enter, type, select, choose, save, submit, click, navigate, validate, check, and verify must remain process nodes unless the evidence explicitly describes branching or alternate outcomes. "
    "Overview is a compact business summary of the same process. "
    "Overview should prefer 5 to 9 nodes when possible. "
    "Overview should group detailed steps into business-level phases, stay mostly linear, and include a decision node only when it is a major business branch that materially changes the flow. "
    "Do not include low-level technical validations in overview unless they are a major business branch. "
    "Detailed must preserve discovered business action order. "
    "Detailed should use one node per evidence-backed business action or explicit decision point. "
    "If the evidence does not clearly support branching, keep the detailed graph linear. "
    "Use concise, professional business labels. "
    "Do not repeat raw transcript wording unnecessarily. "
    "Do not use vague labels like Process Step or Do Action. "
    "Every node must include a valid step_range using the provided step numbers, such as Step 3 or Steps 4-6. "
    "Example linear case: Open SAP -> Enter vendor number -> Enter material details -> Save purchase order. All nodes must be process nodes in one connected linear graph. "
    "Example decision case: Check whether supplier exists -> If supplier does not exist, create supplier -> Continue purchase order creation. A decision node is allowed only because branching is explicit. "
    "Do not return markdown. Return only valid JSON."
)
