export const uiCopy = {
  appTitle: "FlowLens",
  appSubtitle: "Turn recordings and transcripts into structured SOPs, PDDs, and BRDs.",
  workspaceLabel: "Workspace",
  projectsLabel: "My Projects",
  sessionDetailLabel: "Session Detail",
  adminLabel: "Admin",
  metricsLabel: "Metrics",
  aboutLabel: "About",
  loadingSessionSubtitle: "Loading session...",
  loadingApplicationMessage: "Loading application...",
  defaultDraftTitle: "Untitled PDD Session",
  draftTitlePlaceholder: "Invoice processing PDD",
  ownerIdPlaceholder: "Owner username",
  summaryHeadingFallback: "SME Process Walkthrough",
  summarySubheadingFallback: "Process Overview",
  uploadCompletedToast: "Inputs uploaded. Click Generate Draft when you are ready to start processing.",
  generationStartedToast: "PDD generation started. Track progress in My Projects.",
  resumedDraftToast: "Uploaded draft resumed. You can continue with Generate Draft.",
  retryStartedToast: "Draft generation retried. Track progress in My Projects.",
} as const;
